import { Anchor, Box, Divider, List, Stack, Text, Title } from "@mantine/core";

export const AboutPage = () => {
  return (
    <Stack>
      {/* <Title order={2}>About Mantine Theme Builder</Title> */}
      <Box>
        <Title order={3}>🤘 Motivation</Title>
        <Divider my="sm" />
        <Text>
          Mantine is an amazing library with a wide range of components, extensive customization options, and a vibrant
          community. It offers a developer experience unmatched by many React libraries. However, its default styling
          can feel less modern compared to frameworks like shadcn and Radix, which many companies prefer. Setting up
          colors and styles to match those modern aesthetics can be time-consuming and may hinder projects that need a
          quick start.
        </Text>
        <br />
        <Text>
          Enter MantineHub. Initially created as an experimental project to simplify the process of modernizing
          Mantine's styling, MantineHub offers pre-configured themes inspired by Shadcn, Radix, and more. With
          MantineHub, developers can quickly integrate modern styling into their projects by copying and pasting the
          theme configuration.
        </Text>
        <br />
        <Text>
          Due to the overwhelming positive feedback and community endorsment we’ve received, MantineHub has evolved into
          a comprehensive toolkit. It now supports all Mantine components and introduces exciting new features like
          Blocks—pre-built UI components designed to seamlessly work with the generated themes.
        </Text>
      </Box>
      <Box mt="md">
        <Title order={3}>📌 What We Offer</Title>
        <Divider my="sm" />
        <Title order={4}>🎨 Themes</Title>
        <Text>
          Our theme library eliminates the process of creating modern styles for Mantine projects. Choose from a variety
          of predefined themes—like Shadcn-inspired designs, Tailwind-like colors (zinc, amber, rose, and red), and even
          Glassmorphic themes from Radix—and customize them to fit your project needs. The themes are fully compatible
          with all Mantine components, ensuring a cohesive and polished design for your application.
        </Text>
        <br />
        <Title order={4}>🧩 Blocks</Title>
        <Text>
          Blocks are pre-built, ready-to-use UI components designed for specific features that developers can
          effortlessly integrate into their projects. These components work seamlessly with the themes generated by
          MantineHub, saving you time and effort.
          <br />
          Currently, Blocks are an experimental feature with a limited library. Based on user feedback, we plan to
          expand this collection significantly, making it an extensive resource for developers. Contributions and
          feature requests are welcome to help grow this library.
        </Text>
        <br />
        <Title order={4}>⛹️‍♂️ Playground</Title>
        <Text>
          The Playground is an interactive tool that allows you to see how pre-built themes look on individual Mantine
          components. Customize component-specific props—like variant, color, and other features—in real-time and
          explore how each change affects the component's appearance. The Playground ensures you can visualize and
          fine-tune your design choices with ease, making it a valuable addition to the development process.
        </Text>
      </Box>
      {/* <Box mt="lg">
        <Title order={3}>🎨 Understanding the Color Schema</Title>
        <Divider my="sm" />
        <Text>
          Mantine offers a robust and flexible theming system that we have fully leveraged to create modern, cohesive
          designs. The themes and color schemes you see on this site are a result of carefully crafted configurations,
          making it easy to integrate modern aesthetics. Understanding how these variables and customizations work is
          essential to fully unlock the potential of your theme.
        </Text>
        <br />
        <Text>
          To learn about these variables, their roles, and best practices for theming, refer to our detailed blogs where
          we explain the color schema and provide practical examples. Our blogs cover how to approach theming your
          components, how to use these variables effectively, and how to create a cohesive design system for your
          project.
          <br />
          <br />
          We encourage you to read through these articles if you're looking to customize this theme or understand the
          best way to utilize the predefined color variables. This will help you maintain consistency and visual harmony
          throughout your project.
        </Text>
      </Box> */}
      <Box mt={"md"}>
        <Title order={3}>🚀 Future Plans</Title>
        <Divider my="sm" />
        <Text>
          MantineHub(previously, Mantine Theme Builder) is now more than a theming tool—it's an evolving ecosystem for
          Mantine developers. New features are in the pipeline to further enhance the developer experience, streamline
          workflows, and solidify Mantine as the go-to UI library for React projects.
          <br />
          <br />
          Stay tuned for exciting updates, and let us know what features you'd like to see next!
        </Text>
      </Box>
      <Box mt={"md"}>
        <Title order={3}>🧑‍💻 Contributors</Title>
        <Divider my="sm" />
        <Text>
          This project is maintained by{" "}
          <Anchor href="https://github.com/Abhishek-S-Lal" target="_blank">
            Abhishek-S-Lal
          </Anchor>{" "}
          and{" "}
          <Anchor href="https://github.com/gopukr" target="_blank">
            gopukr
          </Anchor>
          . Contributions from the community are welcome and appreciated. Please see our{" "}
          <Anchor href="https://github.com/RubixCube-Innovations/mantine-theme-builder/blob/main/CONTRIBUTING.md">
            CONTRIBUTING.md file
          </Anchor>{" "}
          for more information on how to get involved.
        </Text>
      </Box>
      <Box mt="md">
        <Title order={3}>🤝 Join us</Title>
        <Divider my="sm" />
        <Text>
        MantineHub thrives on community feedback and contributions. If you find MantineHub helpful, please share your thoughts, and request or contribute features. Together, we can make MantineHub a complimentary tool to make UI development with Mantine much more faster and easier.
        </Text>
        <br/>
        <Text>If you find this project useful, please consider</Text>
        <List type="unordered">
          <List.Item icon="⭐️">
            Starring the repository on{" "}
            <Anchor href="https://github.com/RubixCube-Innovations/mantine-theme-builder" target="_blank">
              GitHub
            </Anchor>
          </List.Item>
          <List.Item icon="🫶">Sharing the project with your friends and colleagues</List.Item>
          <List.Item icon="👩‍💻">Contributing to the project</List.Item>
          <Anchor href="https://www.buymeacoffee.com/abhishekslal01" target="_blank">
            <List.Item icon="🥤">Buy me a coffee</List.Item>
          </Anchor>
        </List>
        <br />
      </Box>
    </Stack>
  );
};
